### ISSUE TITLE
Template failure doesn't cause a build failure

### ISSUE THREAD

**Issue by nguillaumin** [mattsheppard/markdown-static-site-generator#7]
When a template is failing the error is reported during the build, but the build still exists with success:

```
----
Tip: If the failing expression is known to be legally refer to something that's sometimes null or missing, either specify a default value like myOptionalVar!myDefault, or use <#if myOptionalVar??>when-present<#else>when-missing</#if>. (These only cover the last step of the expression; to cover the whole expression, use parenthesis: (myOptionalVar.foo)!myDefault, (myOptionalVar.foo)??
----

----
FTL stack trace ("~" means nesting-related):
        - Failed at: ${now?string.yyyy}  [in template "template.ftl" at line 114, column 53]
----
        at freemarker.core.InvalidReferenceException.getInstance(InvalidReferenceException.java:134)
        at freemarker.core.UnexpectedTypeException.newDesciptionBuilder(UnexpectedTypeException.java:80)
        at freemarker.core.UnexpectedTypeException.<init>(UnexpectedTypeException.java:43)
        at freemarker.core.BuiltInsForMultipleTypes$stringBI._eval(BuiltInsForMultipleTypes.java:709)
        at freemarker.core.Expression.eval(Expression.java:81)
        at freemarker.core.Dot._eval(Dot.java:41)
        at freemarker.core.Expression.eval(Expression.java:81)
        at freemarker.core.DollarVariable.calculateInterpolatedStringOrMarkup(DollarVariable.java:96)
        at freemarker.core.DollarVariable.accept(DollarVariable.java:59)
        at freemarker.core.Environment.visit(Environment.java:327)
        at freemarker.core.Environment.visit(Environment.java:333)
        at freemarker.core.Environment.process(Environment.java:306)
        at freemarker.template.Template.process(Template.java:386)
        at com.kstruct.markdown.templating.TemplateProcessor.template(TemplateProcessor.java:65)
        ... 6 more
[INFO] Finished generating doc
[INFO]
[INFO] --- maven-dependency-plugin:2.2:unpack-dependencies (unpack-ftl-documentation) @ product-documentation ---
[INFO] Unpacking /home/nicolas/.m2/repository/com/funnelback/publicui/doc/publicui-doc-freemarker/15.7.1644-SNAPSHOT/publicui-doc-freemarker-15.7.1644-SNAPSHOT-ftl-docs.zip to /home/nicolas/Code/git-checkouts/funnelback-product-documentation/target/generated-site with includes  and excludes
[INFO]
[INFO] --- maven-dependency-plugin:2.2:unpack-dependencies (unpack-modernui-datamodel-javadoc) @ product-documentation ---
[INFO] Unpacking /home/nicolas/.m2/repository/com/funnelback/publicui/publicui-core/15.7.1644-SNAPSHOT/publicui-core-15.7.1644-SNAPSHOT-javadoc.jar to /home/nicolas/Code/git-checkouts/funnelback-product-documentation/target/generated-site/modernui-datamodel with includes  and excludes
[INFO]
[INFO] --- jacoco-maven-plugin:0.7.7.201606060606:report (jacoco-site) @ product-documentation ---
[INFO] Skipping JaCoCo execution due to missing execution data file.
[INFO]
[INFO] --- maven-assembly-plugin:2.3:single (default) @ product-documentation ---
[INFO] Reading assembly descriptor: /home/nicolas/Code/git-checkouts/funnelback-product-documentation/src/assembly/funnelback.xml
[INFO] Building zip: /home/nicolas/Code/git-checkouts/funnelback-product-documentation/target/product-documentation-all.zip
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 15.135 s
[INFO] Finished at: 2016-11-03T09:40:39-07:00
[INFO] Final Memory: 78M/254M
[INFO] ------------------------------------------------------------------------
```

**Comment by mattsheppard** [comment]
Yep - will fix.
